// vpnd/src/network/dns_guard.rs
// DNS leak prevention
//
// When the VPN connects, we:
// 1. Backup /etc/resolv.conf
// 2. Replace it with VPN's DNS server
// 3. Apply firewall rules to block DNS queries on the physical interface
//    (all DNS must go through the VPN tunnel)
// 4. Optionally disable IPv6 to prevent IPv6 DNS/address leaks
// 5. On disconnect: restore everything

use anyhow::{Context, Result};
use std::net::IpAddr;
use std::path::PathBuf;
use tokio::process::Command;
use tracing::{info, warn};

const RESOLV_CONF: &str = "/etc/resolv.conf";
const RESOLV_CONF_BACKUP: &str = "/etc/resolv.conf.vpnforge.bak";

pub struct DnsGuard {
    vpn_dns: IpAddr,
    active: bool,
    ipv6_was_enabled: bool,
    disable_ipv6: bool,
}

impl DnsGuard {
    pub fn new(vpn_dns: IpAddr, disable_ipv6: bool) -> Self {
        Self {
            vpn_dns,
            active: false,
            ipv6_was_enabled: true,
            disable_ipv6,
        }
    }

    /// Apply DNS leak protection
    ///
    /// After this:
    ///   cat /etc/resolv.conf  → shows VPN DNS
    ///   nslookup example.com  → resolves via VPN DNS (no leak)
    pub async fn enable(&mut self) -> Result<()> {
        // 1. Backup current resolv.conf
        self.backup_resolv_conf()?;

        // 2. Write new resolv.conf pointing to VPN DNS
        self.write_vpn_resolv_conf()?;

        // 3. Block DNS on physical interface via firewall
        self.apply_dns_firewall_rules().await?;

        // 4. Optionally disable IPv6 to prevent IPv6 leaks
        if self.disable_ipv6 {
            self.ipv6_was_enabled = self.check_ipv6_enabled()?;
            if self.ipv6_was_enabled {
                self.disable_ipv6_sysctl().await?;
            }
        }

        self.active = true;
        info!(
            dns = %self.vpn_dns,
            ipv6_disabled = self.disable_ipv6,
            "DNS leak protection enabled"
        );
        Ok(())
    }

    /// Remove DNS leak protection and restore original settings
    pub async fn disable(&mut self) -> Result<()> {
        if !self.active {
            return Ok(());
        }

        // Restore resolv.conf
        if let Err(e) = self.restore_resolv_conf() {
            warn!("Failed to restore resolv.conf: {}", e);
        }

        // Remove DNS firewall rules
        if let Err(e) = self.remove_dns_firewall_rules().await {
            warn!("Failed to remove DNS firewall rules: {}", e);
        }

        // Restore IPv6
        if self.disable_ipv6 && self.ipv6_was_enabled {
            if let Err(e) = self.enable_ipv6_sysctl().await {
                warn!("Failed to re-enable IPv6: {}", e);
            }
        }

        self.active = false;
        info!("DNS leak protection disabled, original DNS restored");
        Ok(())
    }

    pub fn is_active(&self) -> bool {
        self.active
    }

    // ──────────────────────────────────────────────────────────────────────────
    //  DNS configuration
    // ──────────────────────────────────────────────────────────────────────────

    fn backup_resolv_conf(&self) -> Result<()> {
        if std::path::Path::new(RESOLV_CONF).exists() {
            std::fs::copy(RESOLV_CONF, RESOLV_CONF_BACKUP)
                .context("Failed to backup /etc/resolv.conf")?;
            info!("Backed up {} to {}", RESOLV_CONF, RESOLV_CONF_BACKUP);
        }
        Ok(())
    }

    fn write_vpn_resolv_conf(&self) -> Result<()> {
        let content = format!(
            "# Generated by VPNForge — DNS leak protection active\n\
             # Original backed up to {}\n\
             nameserver {}\n\
             options ndots:0\n",
            RESOLV_CONF_BACKUP, self.vpn_dns
        );

        std::fs::write(RESOLV_CONF, content)
            .context("Failed to write VPN DNS to /etc/resolv.conf")?;

        info!(dns = %self.vpn_dns, "DNS configured via /etc/resolv.conf");
        Ok(())
    }

    fn restore_resolv_conf(&self) -> Result<()> {
        if std::path::Path::new(RESOLV_CONF_BACKUP).exists() {
            std::fs::copy(RESOLV_CONF_BACKUP, RESOLV_CONF)
                .context("Failed to restore /etc/resolv.conf")?;
            std::fs::remove_file(RESOLV_CONF_BACKUP).ok();
            info!("Restored original /etc/resolv.conf");
        }
        Ok(())
    }

    // ──────────────────────────────────────────────────────────────────────────
    //  DNS firewall rules (prevent DNS queries bypassing VPN)
    // ──────────────────────────────────────────────────────────────────────────

    async fn apply_dns_firewall_rules(&self) -> Result<()> {
        // Block DNS (UDP/TCP port 53) on physical interface output
        // DNS queries must go through the VPN tunnel (tun0)
        // nftables rule: drop DNS if not going through tun0
        let ruleset = format!(
            r#"table inet vpnforge_dns_guard {{
    chain output {{
        type filter hook output priority -50; policy accept;
        oif != "lo" oif != "tun0" udp dport 53 drop
        oif != "lo" oif != "tun0" tcp dport 53 drop
    }}
}}"#
        );

        // Write to a restricted directory owned by root, not world-writable /tmp.
        // This prevents local privilege escalation via symlink attacks.
        let tmp = format!("/run/vpnd/dns_{}.nft", std::process::id());
        std::fs::write(&tmp, &ruleset)
            .context("Failed to write DNS guard ruleset")?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let _ = std::fs::set_permissions(&tmp, std::fs::Permissions::from_mode(0o600));
        }

        let output = Command::new("nft")
            .args(["-f", &tmp])
            .output()
            .await;

        std::fs::remove_file(&tmp).ok();

        // DNS firewall is a critical security control — failure means traffic can
        // bypass the VPN and leak the user's real DNS queries. Log a prominent
        // warning so the user and admin are always aware if protection is inactive.
        match output {
            Ok(o) if o.status.success() => {
                info!("DNS firewall rules applied — DNS queries forced through VPN");
            }
            Ok(o) => {
                let err = String::from_utf8_lossy(&o.stderr);
                warn!(
                    "SECURITY WARNING: DNS firewall rules could not be applied (nftables error: {}). \
                     DNS queries may leak outside the VPN tunnel. \
                     Ensure nftables is installed and the daemon has CAP_NET_ADMIN.",
                    err
                );
            }
            Err(e) => {
                warn!(
                    "SECURITY WARNING: nft binary not found ({}). \
                     DNS leak protection is NOT active — DNS queries may leak outside the VPN tunnel.",
                    e
                );
            }
        }

        Ok(())
    }

    async fn remove_dns_firewall_rules(&self) -> Result<()> {
        let _ = Command::new("nft")
            .args(["delete", "table", "inet", "vpnforge_dns_guard"])
            .output()
            .await;
        Ok(())
    }

    // ──────────────────────────────────────────────────────────────────────────
    //  IPv6 management
    // ──────────────────────────────────────────────────────────────────────────

    fn check_ipv6_enabled(&self) -> Result<bool> {
        let content = std::fs::read_to_string("/proc/sys/net/ipv6/conf/all/disable_ipv6")
            .unwrap_or_else(|_| "0\n".into());
        Ok(content.trim() == "0")
    }

    async fn disable_ipv6_sysctl(&self) -> Result<()> {
        Command::new("sysctl")
            .args(["-w", "net.ipv6.conf.all.disable_ipv6=1"])
            .output()
            .await
            .context("Failed to disable IPv6 via sysctl")?;
        Command::new("sysctl")
            .args(["-w", "net.ipv6.conf.default.disable_ipv6=1"])
            .output()
            .await
            .context("Failed to disable IPv6 default via sysctl")?;
        info!("IPv6 disabled to prevent IPv6 leaks");
        Ok(())
    }

    async fn enable_ipv6_sysctl(&self) -> Result<()> {
        Command::new("sysctl")
            .args(["-w", "net.ipv6.conf.all.disable_ipv6=0"])
            .output()
            .await
            .context("Failed to re-enable IPv6 via sysctl")?;
        Command::new("sysctl")
            .args(["-w", "net.ipv6.conf.default.disable_ipv6=0"])
            .output()
            .await
            .context("Failed to re-enable IPv6 default via sysctl")?;
        info!("IPv6 re-enabled");
        Ok(())
    }
}

impl Drop for DnsGuard {
    fn drop(&mut self) {
        if self.active {
            warn!("DnsGuard dropped while active — restoring DNS");
            // Sync restore — this is critical
            if std::path::Path::new(RESOLV_CONF_BACKUP).exists() {
                let _ = std::fs::copy(RESOLV_CONF_BACKUP, RESOLV_CONF);
                let _ = std::fs::remove_file(RESOLV_CONF_BACKUP);
            }
        }
    }
}
